2024-09-07 10:46:03,024 - ERROR - Validation error at index 377: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,096 - ERROR - Validation error at index 827: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NWS3P2W38H', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: GTC9KBWJO9', 'input': 'GTC9KBWJO9', 'ctx': {'error': ValueError('Invalid date format: GTC9KBWJO9')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,099 - ERROR - Validation error at index 847: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,106 - ERROR - Validation error at index 884: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,197 - ERROR - Validation error at index 1443: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': '8YJ3TYH6Z5', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: DJIXF1AFAZ', 'input': 'DJIXF1AFAZ', 'ctx': {'error': ValueError('Invalid date format: DJIXF1AFAZ')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,350 - ERROR - Validation error at index 2418: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,362 - ERROR - Validation error at index 2489: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,415 - ERROR - Validation error at index 2830: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,552 - ERROR - Validation error at index 3694: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'ACT9K6ECRJ', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: H2PCQP4W50', 'input': 'H2PCQP4W50', 'ctx': {'error': ValueError('Invalid date format: H2PCQP4W50')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,629 - ERROR - Validation error at index 4196: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,631 - ERROR - Validation error at index 4208: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'WDWMN9TU45', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: XTD27ANR5Q', 'input': 'XTD27ANR5Q', 'ctx': {'error': ValueError('Invalid date format: XTD27ANR5Q')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,740 - ERROR - Validation error at index 4916: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'VNLNMWPJII', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: 7VGB4DA1WI', 'input': '7VGB4DA1WI', 'ctx': {'error': ValueError('Invalid date format: 7VGB4DA1WI')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,861 - ERROR - Validation error at index 5686: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,917 - ERROR - Validation error at index 6024: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,013 - ERROR - Validation error at index 6653: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': '4FI5GTUVYG', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: RLQYRRYHPU', 'input': 'RLQYRRYHPU', 'ctx': {'error': ValueError('Invalid date format: RLQYRRYHPU')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,117 - ERROR - Validation error at index 7332: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'RF1ACW165R', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: T008RE1ZR6', 'input': 'T008RE1ZR6', 'ctx': {'error': ValueError('Invalid date format: T008RE1ZR6')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,142 - ERROR - Validation error at index 7493: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': '6JJKS7R0WA', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: 7FL8EU9GBF', 'input': '7FL8EU9GBF', 'ctx': {'error': ValueError('Invalid date format: 7FL8EU9GBF')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,193 - ERROR - Validation error at index 7818: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'XRPE6C4GS9', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: GD9PHJXQR4', 'input': 'GD9PHJXQR4', 'ctx': {'error': ValueError('Invalid date format: GD9PHJXQR4')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,604 - ERROR - Validation error at index 10457: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': '5VN8HOLMVE', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: WCK463ZO1Z', 'input': 'WCK463ZO1Z', 'ctx': {'error': ValueError('Invalid date format: WCK463ZO1Z')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,745 - ERROR - Validation error at index 11345: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'Q7VGWP7LH9', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: OE3KONN2V6', 'input': 'OE3KONN2V6', 'ctx': {'error': ValueError('Invalid date format: OE3KONN2V6')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,765 - ERROR - Validation error at index 11465: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'ZBGGFGY4H0', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: T995FX2C7W', 'input': 'T995FX2C7W', 'ctx': {'error': ValueError('Invalid date format: T995FX2C7W')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,770 - ERROR - Validation error at index 11499: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'UMR9FIE22M', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: EVVMMB3QYV', 'input': 'EVVMMB3QYV', 'ctx': {'error': ValueError('Invalid date format: EVVMMB3QYV')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,987 - ERROR - Validation error at index 12876: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:05,115 - ERROR - Validation error at index 13708: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:05,303 - ERROR - Validation error at index 14884: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': '2ANT8LW3I5', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: UZGSD0AEBT', 'input': 'UZGSD0AEBT', 'ctx': {'error': ValueError('Invalid date format: UZGSD0AEBT')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:51,366 - ERROR - Failed to retrieve data for store number 451: 500 Server Error: Internal Server Error for url: https://aqj7u5id95.execute-api.eu-west-1.amazonaws.com/prod/store_details/451
2024-09-07 10:46:51,384 - ERROR - Validation error at index 63: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': '1ZVU03X2P6', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: ZCXWWKF45G', 'input': 'ZCXWWKF45G', 'ctx': {'error': ValueError('Invalid date format: ZCXWWKF45G')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': '1CJ5OAU4BR', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'YELVM536YT', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,409 - ERROR - Validation error at index 172: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'Q1TJY8H1ZH', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: 7AHXLXIUEF', 'input': '7AHXLXIUEF', 'ctx': {'error': ValueError('Invalid date format: 7AHXLXIUEF')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': '3ZR3F89D97', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'FP8DLXQVGH', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,418 - ERROR - Validation error at index 217: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'NULL', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('staff_numbers',), 'msg': 'Value error, Invalid staff number: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid staff number: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'NULL', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,421 - ERROR - Validation error at index 231: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': '2YBZ1440V6', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: 0OLAK2I6NS', 'input': '0OLAK2I6NS', 'ctx': {'error': ValueError('Invalid date format: 0OLAK2I6NS')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'L13EQEQODP', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'HMHIFNLOBN', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,443 - ERROR - Validation error at index 333: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'O7NF1FZ74Y', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: A3PMVM800J', 'input': 'A3PMVM800J', 'ctx': {'error': ValueError('Invalid date format: A3PMVM800J')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'J3BPB68Z1J', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'F3AO8V2LHU', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,453 - ERROR - Validation error at index 381: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'SKO4NMRNNF', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: GMMB02LA9V', 'input': 'GMMB02LA9V', 'ctx': {'error': ValueError('Invalid date format: GMMB02LA9V')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'AJHOMDOHZ4', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'OH20I92LX3', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,458 - ERROR - Validation error at index 405: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'NULL', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('staff_numbers',), 'msg': 'Value error, Invalid staff number: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid staff number: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'NULL', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,460 - ERROR - Validation error at index 414: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'ID819KG3X5', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: 13PIY8GD1H', 'input': '13PIY8GD1H', 'ctx': {'error': ValueError('Invalid date format: 13PIY8GD1H')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'AE7EEW4HSS', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'OYVW925ZL8', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,465 - ERROR - Validation error at index 437: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'NULL', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('staff_numbers',), 'msg': 'Value error, Invalid staff number: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid staff number: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'NULL', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,468 - ERROR - Validation error at index 447: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'K8CXLZDP07', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: 36IIMAQD58', 'input': '36IIMAQD58', 'ctx': {'error': ValueError('Invalid date format: 36IIMAQD58')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'JZP8MIJTPZ', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'B3EH2ZGQAV', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:52,049 - ERROR - Validation error at index 266: [{'type': 'string_type', 'loc': ('product_name',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('product_price',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('weight',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('category',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('EAN',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('date_added',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('uuid',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('removed',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('product_code',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}]
2024-09-07 10:46:52,138 - ERROR - Validation error at index 751: [{'type': 'value_error', 'loc': ('product_price',), 'msg': 'Value error, Invalid product price format', 'input': 'XCD69KUI0K', 'ctx': {'error': ValueError('Invalid product price format')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('EAN',), 'msg': 'Value error, EAN should only contain digits', 'input': 'OO7KH8P79I', 'ctx': {'error': ValueError('EAN should only contain digits')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_added',), 'msg': 'Value error, Invalid date format: CCAVRB79VV', 'input': 'CCAVRB79VV', 'ctx': {'error': ValueError('Invalid date format: CCAVRB79VV')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('uuid',), 'msg': 'Value error, Invalid UUID format', 'input': '7QB0Z9EW1G', 'ctx': {'error': ValueError('Invalid UUID format')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('removed',), 'msg': "Value error, Removed status should be 'Still_avaliable' or 'Removed'", 'input': 'T3QRRH7SRP', 'ctx': {'error': ValueError("Removed status should be 'Still_avaliable' or 'Removed'")}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:52,145 - ERROR - Validation error at index 788: [{'type': 'string_type', 'loc': ('product_name',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('product_price',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('weight',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('category',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('EAN',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('date_added',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('uuid',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('removed',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('product_code',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}]
2024-09-07 10:46:52,146 - ERROR - Validation error at index 794: [{'type': 'string_type', 'loc': ('product_name',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('product_price',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('weight',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('category',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('EAN',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('date_added',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('uuid',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('removed',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('product_code',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}]
2024-09-07 10:46:52,209 - ERROR - Validation error at index 1133: [{'type': 'value_error', 'loc': ('product_price',), 'msg': 'Value error, Invalid product price format', 'input': 'N9D2BZQX63', 'ctx': {'error': ValueError('Invalid product price format')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('EAN',), 'msg': 'Value error, EAN should only contain digits', 'input': 'E8EOGWOY8S', 'ctx': {'error': ValueError('EAN should only contain digits')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_added',), 'msg': 'Value error, Invalid date format: 09KREHTMWL', 'input': '09KREHTMWL', 'ctx': {'error': ValueError('Invalid date format: 09KREHTMWL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('uuid',), 'msg': 'Value error, Invalid UUID format', 'input': 'CP8XYQVGGU', 'ctx': {'error': ValueError('Invalid UUID format')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('removed',), 'msg': "Value error, Removed status should be 'Still_avaliable' or 'Removed'", 'input': 'BPSADIOQOK', 'ctx': {'error': ValueError("Removed status should be 'Still_avaliable' or 'Removed'")}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:52,257 - ERROR - Validation error at index 1400: [{'type': 'value_error', 'loc': ('product_price',), 'msg': 'Value error, Invalid product price format', 'input': 'ODPMASE7V7', 'ctx': {'error': ValueError('Invalid product price format')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('weight',), 'msg': 'Value error, Weight must be in kg or g', 'input': 'MX180RYSHX', 'ctx': {'error': ValueError('Weight must be in kg or g')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('EAN',), 'msg': 'Value error, EAN should only contain digits', 'input': 'BHPF2JTNKQ', 'ctx': {'error': ValueError('EAN should only contain digits')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_added',), 'msg': 'Value error, Invalid date format: PEPWA0NCVH', 'input': 'PEPWA0NCVH', 'ctx': {'error': ValueError('Invalid date format: PEPWA0NCVH')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('uuid',), 'msg': 'Value error, Invalid UUID format', 'input': 'VIBLHHVPMN', 'ctx': {'error': ValueError('Invalid UUID format')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('removed',), 'msg': "Value error, Removed status should be 'Still_avaliable' or 'Removed'", 'input': 'H5N71TV8AY', 'ctx': {'error': ValueError("Removed status should be 'Still_avaliable' or 'Removed'")}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:52,304 - ERROR - Validation error at index 1660: [{'type': 'string_type', 'loc': ('product_name',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('product_price',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('weight',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('category',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('EAN',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('date_added',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('uuid',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('removed',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('product_code',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}]
